// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Main module

	public static java.lang.String getconst_admin_password()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Main.const_admin_password");
	}

	/**
	* 0.0.1
	* * Initial Version
	*/
	public static java.lang.String getconst_version()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Main.const_version");
	}
}